DECLARE @waz_anteil FLOAT = 0.985 ;
DECLARE @saldo FLOAT = -11.82 ;
SELECT STR_ALTERNATIVTEXTFUERBARRIERE ,STRID
From
    ZE_KAT_SALDENKONTROLLE
WHERE
				CASE WHEN FLT_UNTERGRENZE * @waz_anteil IS NULL THEN
					-9999999999999
				ELSE
					FLT_UNTERGRENZE * @waz_anteil
				END <= @saldo AND @saldo <=
				CASE WHEN FLT_OBERGRENZE * @waz_anteil IS NULL THEN
					99999999999999999999
				ELSE
					FLT_OBERGRENZE * @waz_anteil
				END
ORDER BY ABS(FLT_UNTERGRENZE) DESC
