export const deleteAllZEDataByUserIdQuery = (userID) => {
  return `
DELETE FROM ZE_T_M_D_ZEITEN WHERE "FKSTRID"=ANY(SELECT "STRID" FROM "ZE_T_M_DATUM" WHERE "FKSTRID"=ANY(SELECT "STRID" FROM "ZE_T_MONAT" WHERE "REF_BENUTZER"=${userID}));
DELETE FROM ZE_T_M_DATUM WHERE "FKSTRID"=ANY(SELECT "STRID" FROM "ZE_T_MONAT" WHERE "REF_BENUTZER"=${userID});
DELETE FROM ZE_T_MONAT WHERE "REF_BENUTZER"=${userID};
`;
};
// DELETE FROM "ZE_T_QUARTALSBERICHT";
export const deleteAllZEDataQuery = () => {
  return `

  DELETE FROM ZE_T_M_D_ZEITEN;
  DELETE FROM ZE_T_M_DATUM;
  DELETE FROM ZE_T_M_JOURNAL;
  DELETE FROM ZE_T_M_MASSNAHMEN;
  DELETE FROM ZE_T_MONAT;
  `;
};
